import { TTSVoice } from "./types";

export const CURATED_VOICES: TTSVoice[] = [
  {
    id: "EXAVITQu4vr4xnSDxMaL",
    name: "Bella",
    category: "Energetic",
    language: "English (US)",
    accent: "American Modern",
    gender: "female",
    description: "Dynamic, upbeat, and modern cadence built for fast-paced viral reels.",
  },
  {
    id: "pNInz6obpgDQGcFmaJgB",
    name: "Adam",
    category: "Cinematic",
    language: "English (US)",
    accent: "American Deep",
    gender: "male",
    description: "Deep, authoritative, and cinematic voice ideal for high-impact viral hooks.",
  },
  {
    id: "ErXwobaYiN019PkySvjV",
    name: "Antoni",
    category: "Conversational",
    language: "English (US)",
    accent: "American Casual",
    gender: "male",
    description: "Warm, engaging, and conversational for authentic storytelling & TikToks.",
  },
  {
    id: "Xb7hH8MSUJpSbSDYk0k2",
    name: "Alice",
    category: "Natural",
    language: "English (UK)",
    accent: "British Confident",
    gender: "female",
    description: "Clear, poised, and articulate narration suited for explainers and tutorials.",
  },
  {
    id: "JBFqnCBsd6RMkjVDRZzb",
    name: "George",
    category: "Storyteller",
    language: "English (UK)",
    accent: "British Warm",
    gender: "male",
    description: "Warm, resonant, and engaging tone for long-form narrative breakdowns.",
  },
  {
    id: "FGY2WhTYpPnrIDTdsKH5",
    name: "Laura",
    category: "Energetic",
    language: "English (US)",
    accent: "American Bright",
    gender: "female",
    description: "High-energy, enthusiastic, and approachable tone for lifestyle & product videos.",
  },
  {
    id: "N2lVS1w4EtoT3dr4eOWO",
    name: "Callum",
    category: "Cinematic",
    language: "English (US)",
    accent: "American Intense",
    gender: "male",
    description: "Intense, commanding pacing ideal for action, drama, and documentary trailers.",
  },
  {
    id: "pFZP5JQG7iQjIQuC4Bku",
    name: "Lily",
    category: "Natural",
    language: "English (UK)",
    accent: "British Velvety",
    gender: "female",
    description: "Gentle, velvety, and clear cadence perfect for calming storytelling.",
  },
];
