import { VeeloxIdea } from "./types";
import { AIProvider, getAIProvider } from "./aiProvider";

export async function generateIdeas(
  topic: string,
  niche: string,
  apiKey?: string | null
): Promise<{ ideas: VeeloxIdea[]; isDevelopmentMode: boolean }> {
  const provider = getAIProvider(apiKey);
  const isDevelopmentMode = !apiKey || apiKey.trim().length === 0;

  if (isDevelopmentMode) {
    // Return high quality structured ideas generated by the development engine
    const cleanTopic = topic.trim() || "AI Content Creation";
    const cleanNiche = niche.trim() || "Technology";

    const ideas: VeeloxIdea[] = [
      {
        id: "idea_1",
        title: `How ${cleanTopic} is Quietly Changing Everything`,
        hook: `You won't believe what happened with ${cleanTopic} this week... and nobody is talking about it.`,
        angle: "Insider analysis exposing the underlying structural shift and immediate creator impact.",
        targetAudience: "Creators, tech enthusiasts, and early adopters wanting an edge.",
        format: "Shorts",
        estimatedDuration: 45,
        reasoning: "High-curiosity hook with strong retention potential on vertical feeds.",
        platform: "YouTube Shorts / TikTok",
      },
      {
        id: "idea_2",
        title: `The Beginner's Blueprint to ${cleanTopic}`,
        hook: `Stop overcomplicating ${cleanTopic}. Here are the only 3 steps you actually need.`,
        angle: "Step-by-step simplification breaking down complex technical concepts into actionable workflows.",
        targetAudience: "Beginners feeling overwhelmed by information overload.",
        format: "Tutorial",
        estimatedDuration: 60,
        reasoning: "Educational search-intent captures high watch time and repeat saves.",
        platform: "Instagram Reels / YouTube",
      },
      {
        id: "idea_3",
        title: `Why 99% of People Are Wrong About ${cleanTopic}`,
        hook: `Everyone says ${cleanTopic} is the future, but they're completely missing the real problem.`,
        angle: "Contrarian debate challenging conventional wisdom with hard numbers and counter-examples.",
        targetAudience: "Critical thinkers looking for objective viewpoints rather than hype.",
        format: "Commentary",
        estimatedDuration: 55,
        reasoning: "Contrarian angles trigger comment debates and platform algorithmic virality.",
        platform: "TikTok / X",
      },
      {
        id: "idea_4",
        title: `Top 5 ${cleanTopic} Hacks That Feel Illegal to Know`,
        hook: `If you're still doing this manually, you're wasting 10 hours every single week.`,
        angle: "Fast-paced listicle packed with rapid-fire tool tips and immediate productivity wins.",
        format: "Shorts",
        targetAudience: "Busy professionals and digital creators seeking time-saving leverage.",
        estimatedDuration: 50,
        reasoning: "High utility and save-rate driving organic algorithmic distribution.",
        platform: "YouTube Shorts / Reels",
      },
    ];

    return { ideas, isDevelopmentMode: true };
  }

  // Real AI Mode using Groq / LLM
  try {
    const prompt = `You are a viral video strategist for the creator platform Veelox.
Generate 4 distinct video ideas for this trending topic: "${topic}" in the "${niche}" niche.
Return ONLY a valid JSON object with the key "ideas" containing an array of 4 objects with these exact keys:
- id: string (e.g. "idea_1")
- title: string (viral, high CTR title)
- hook: string (irresistible opening hook line)
- angle: string (unique perspective or framing)
- targetAudience: string (who this speaks to)
- format: "Shorts" | "Reels" | "TikTok" | "Long-form" | "Explainer" | "Tutorial"
- estimatedDuration: number (in seconds between 30 and 90)
- reasoning: string (why this will perform well)
- platform: string (primary platform)`;

    const raw = await provider.complete({
      systemPrompt: "You are an elite video content director. Return valid JSON only.",
      userPrompt: prompt,
      jsonMode: true,
    });

    const parsed = JSON.parse(raw);
    const ideas: VeeloxIdea[] = (parsed.ideas ?? []).map((item: any, idx: number) => ({
      id: item.id || `idea_${idx + 1}`,
      title: item.title || `Mastering ${topic}`,
      hook: item.hook || `Here is why ${topic} is blowing up right now.`,
      angle: item.angle || "Deep dive into the trend mechanics.",
      targetAudience: item.targetAudience || "General audience",
      format: item.format || "Shorts",
      estimatedDuration: Number(item.estimatedDuration) || 60,
      reasoning: item.reasoning || "High audience curiosity",
      platform: item.platform || "YouTube Shorts",
    }));

    return { ideas, isDevelopmentMode: false };
  } catch (err) {
    console.warn("AI Idea generation failed, falling back to development ideas:", err);
    return generateIdeas(topic, niche, null);
  }
}
